### ISSUE TITLE
Please make sure resend is working

### ISSUE THREAD

**Issue by thomastom99** [thomastom99/fto#9]
Please make sure resend is working with correct user name and password.

 If the user didnt registered (by clicking on he confirmation link and entering into the control panel and saving the details), the the resend should send the User registration request message which was send earlier. Else it should send the Login name and password in the mail..

**Comment by jithinmohanan** [comment]
Resend is working now. Only Signed up shop owners are listed in shop owners gird view. For binding that gridview ,we need more details of shopowner rather than the email id and password. As per the existing system, registered users (but not signed up successfully)  can't show in gridview because of email id does not showing in gridview .

**Comment by thomastom99** [comment]
then leave that option for now.. will do that in next version..
